### ISSUE TITLE
Okay to publish?

### ISSUE THREAD

**Issue by Gerardwx** [bradleyharden/nmrpeaklists#1]
We've been asked to install this on [NMRbox](https://nmrbox.nmrhub.org).

Can we push it up to pypi.org? It's easier for us to install Python packages from there.

**Comment by bradleyharden** [comment]
Hi @Gerardwx,

I haven't thought about this code in years. I'm also surprised to learn that anyone is actually using it. Is the request coming from descendants of the Frueh lab? Or has the code somehow made it out into the wider ecosystem?

This is far from my best code, and I literally laughed out loud when I read this gem from the README:

> Currently in final testing.

But if people find it useful, I would be glad to push it to PyPI. I've only ever pushed packages to my company's internal Artifactory repo, so I don't have any direct experience with PyPI. But I will figure it out and push it this week.

**Comment by Gerardwx** [comment]
The request was from Dominique Frueh.

I did a test push (after lowering the version number, since pypi is picky about that), and it just worked. So it should just be a matter of creating the pypi account.

https://test.pypi.org/project/nmrpeaklists/0.0.0/

**Comment by bradleyharden** [comment]
I created an account last night. I will try to find some time this week to get it pushed.

**Comment by bradleyharden** [comment]
It's now [live](https://pypi.org/project/nmrpeaklists/) on PyPI. Let me know if you have any further issues or requests.
